### ISSUE TITLE
Transparent proxying and DNS resolution

### ISSUE THREAD

**Issue by aidansteele** [linkerd/linkerd-inject#9]
Hi folks,

I love the work you're doing and I am considering implementing `linkerd` in our stack. One of the selling points for me is the transparent proxy support, which is especially important as we have some legacy applications that simply do not work with `http_proxy` configuration (or HTTP proxies full stop).

Interestingly, we actually have a need to run a HTTP proxy (rules imposed by the security team), so we transparently proxy outbound traffic using a combination of `iptables` rules and Squid. 

This works well, but requires DNS to be resolvable by the application, as name resolution occurs before the HTTP request. How do you deal with this? In #1 there is this note, but I struggle to find any elaboration:

> When the services call each other, the service names need to be resolvable by kubedns so that the packet has an IP and can be routed (hence renaming world-v1 to world).

Does this depend on "kubedns"? Apologies for the lack of understanding, my only container scheduler experience is limited to AWS' EC2 Container Service. How would you implement this outside of K8s? Right now my guess is maybe install `dnsmasq`, make *all* resolution resolve to some made-up address (169.254.x.x.) and have `iptables` forward the traffic to `linkerd`. Does that sound doable?

**Comment by rmars** [comment]
Hi @aidansteele! Yep, you are correct! Our current implementation is k8s specific. we deal with the resolution issue by using the Kubernetes DNS server to resolve the name ([documentation here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) and also see the DNS section of [this](https://kubernetes.io/docs/concepts/services-networking/service/) for details on how that works in k8s). 

So in the demo, when the hello service calls world (e.g. `http://world:7778`), kubernetes will resolve `world.default.svc.cluster.local` to the virtual IP of the world service, and then when the application makes a request to that IP, our `iptables` rules send the traffic to linkerd.

What you propose with `dnsmasq` sounds reasonable to me. Yeah, the problem is, as you said, getting an IP address before making the request. Once you have that you could do something like what we do in the minikube section of https://github.com/linkerd/linkerd-inject/blob/master/docker/prepare_proxy.sh to forward all traffic to linkerd.

```
iptables -t nat -A OUTPUT -d 127.0.0.1/32 -j RETURN
iptables -t nat -A OUTPUT -p tcp -j DNAT --to ${LINKERD_IP}:${LINKERD_PORT}
```

hope that helps!

**Comment by aidansteele** [comment]
Hi @rmars, thank you for your _astonishingly_ speedy and helpful response!

Thank you for the explanation, links to documentation and validation of my rough idea. I will give that a shot some time today and report back whether it works as planned. I've got a couple more questions if you don't mind!

* How well does the transparent proxying work when the application makes HTTPS requests? Right now our outbound "proxifier" uses SO_ORIGINAL_DST to determine where the original traffic was intended and then wraps it up in a `CONNECT <ip>:443` on the way out. Can `linkerd` transparently pass through this traffic? (This would mean we wouldn't need exceptions in the `dnsmasq` rules to _not_ send e.g. AWS traffic through `linkerd`)

* Does `linkerd` support upstream HTTP proxies? My google-fu fails me and I can't find if this is supported. We need this because we use a HTTP proxy to cross AWS account boundaries between teams.

* I'm not super strong with `iptables`, but right now we are using the following rules:

```
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8888
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to 8888
iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to 8888
iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to 8888
```

The first two rules appear to be needed for proxifying traffic from Docker containers on the host - the OUTPUT rules don't seem to apply to them. How does this differ to your rules with the `-j DNAT` - is the distinction meaningful?

**Comment by rmars** [comment]
Hi @aidansteele! No problem! Let us know how it goes! To your questions:

* unfortunately linkerd doesn't do CONNECT tunneling. you can use linkerd to [initiate/terminate TLS](https://linkerd.io/features/tls/) but not to proxy it.

* you can use linkerd with other proxies. [This blog post](https://buoyant.io/2016/11/18/a-service-mesh-for-kubernetes-part-v-dogfood-environments-ingress-and-edge-routing/) has an example of using linkerd and NGINX together.

* the rules that we use in [prepare_proxy.sh](https://github.com/linkerd/linkerd-inject/blob/master/docker/prepare_proxy.sh) forward outgoing traffic to linkerd. The rules that you have direct both incoming and outgoing traffic through your proxy. Our prepare_proxy.sh assumes you're running linkerd as a daemonset in k8s (i.e. per host). Linkerd knows how to find the services, so all we need for transparent proxying is to ensure that service-to-service communication goes through linkerd.  Your rules will depend on how you are going to deploy the proxy:
  - In the daemonset setup, then, if `hello` calls `world`, the request is sent (by the `iptables` rules) to the `outgoing` router of the linkerd on hello's host, and is routed to the incoming router of the host on which `world` is running. The linkerd on the world host then sends the request to the world service. So for the per host case, we only need to change the outbound rules. 
  - If you're running linkerd as a sidecar (alongside application instances) then iirc you want to proxy both incoming and outgoing traffic through linkerd (the [Istio prepare_proxy](https://github.com/istio/pilot/blob/master/docker/prepare_proxy.sh) has an example of setting up iptables rules to send traffic to a sidecar proxy).

**Comment by rmars** [comment]
Gonna close out this issue, feel free to chat more on https://discourse.linkerd.io/!
